---
# tasks file for ansible-role-postgre-install
- name: Install PostgreSQL
  package:
    name: postgresql
    state: present

- name: Copy postgresql.conf from role to remote machine
  copy:
    src: postgresql.conf
    dest: "{{ postgresql_data_directory }}/postgresql.conf"
  tags: 
    - copy_postgresql_conf

- name: Copy pg_hba.conf from role to remote machine
  copy:
    src: pg_hba.conf
    dest: "{{ postgresql_data_directory }}/pg_hba.conf"
  tags: 
    - copy_pg_hba_conf

# Handlers
- name: restart postgresql
  service:
    name: postgresql
    state: restarted


- name: Check PostgreSQL connectivity
  become: yes
  become_user: postgres
  shell: psql -U postgres -c "SELECT 1;"
  register: postgresql_check_result
  
- debug:
    msg: "PostgreSQL is {{ 'not ' if postgresql_check_result.rc != 0 else '' }}running."