---
# tasks file for ansible-role-postgre-install
- name: Configure PostgreSQL to accept external connections
  block:
    - name: Set listen_addresses in postgresql.conf
      lineinfile:
        path: "{{ postgresql_data_directory }}/postgresql.conf"
        regexp: '^#?listen_addresses =.*$'
        line: "listen_addresses = '*'"
      notify:
        - restart postgresql

    - name: Add host access in pg_hba.conf
      lineinfile:
        path: "{{ postgresql_data_directory }}/pg_hba.conf"
        line: "host    all             all             0.0.0.0/0               trust"
      notify:
        - restart postgresql

  tags: configure_postgresql
