---
# tasks file for ansible-role-postgre-install

# Задачи для установки PostgreSQL
- name: Install PostgreSQL
  become: true
  package:
    name: postgresql
    state: present

# Копирование конфигурационных файлов PostgreSQL
- name: Copy postgresql.conf from role to remote machine
  become: true
  copy:
    src: postgresql.conf
    dest: "{{ postgresql_data_directory }}/postgresql.conf"
  tags: 
    - copy_postgresql_conf

- name: Copy pg_hba.conf from role to remote machine
  become: true
  copy:
    src: pg_hba.conf
    dest: "{{ postgresql_data_directory }}/pg_hba.conf"
  tags: 
    - copy_pg_hba_conf

# Handlers
- name: restart postgresql
  become: true  
  service:
    name: postgresql
    state: restarted
